buildscript {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.ornithemc.net/releases' }
    }

    dependencies {
        classpath "fabric-loom:fabric-loom.gradle.plugin:$loomVersion"
        classpath "ploceus:ploceus.gradle.plugin:$loomVersion"
    }
}

apply plugin: 'fabric-loom'
apply plugin: 'ploceus'

ploceus {
    setIntermediaryGeneration(2)
}

repositories {
    maven { url = 'https://maven.legacyfabric.net' }
}

dependencies {
    implementation project(':worldedit-core')

    minecraft "com.mojang:minecraft:$minecraftVersion"
    mappings ploceus.featherMappings(featherBuild)
    modImplementation "net.fabricmc:fabric-loader:$loaderVersion"
    modImplementation "net.legacyfabric.legacy-fabric-api:legacy-fabric-api:$fabricApiVersion"
}

processResources {
    filesMatching('fabric.mod.json') {
        expand(
                internalVersion: version,
                minecraftVersion: minecraftVersion,
                loaderVersion: loaderVersion,
                fabricApiVersion: fabricApiVersion
        )
    }
}