buildscript {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net' }
        maven { url = 'https://maven.ornithemc.net/releases' }
    }

    dependencies {
        classpath "net.fabricmc.fabric-loom-remap:net.fabricmc.fabric-loom-remap.gradle.plugin:$loomVersion"
        classpath "ploceus:ploceus.gradle.plugin:$loomVersion"
    }
}

apply plugin: 'net.fabricmc.fabric-loom-remap'
apply plugin: 'ploceus'

String minecraftVersion = '1.8.9' // TODO: Multi-version

ploceus {
    setIntermediaryGeneration(2)
}

dependencies {
    implementation project(':worldedit-core')

    minecraft "com.mojang:minecraft:$minecraftVersion"
    modImplementation "net.fabricmc:fabric-loader:$loaderVersion"
    mappings ploceus.featherMappings(featherVersion)
}

processResources {
    filesMatching('fabric.mod.json') {
        expand 'internalVersion': version
    }
}

shadowJar {
    dependencies {
        include project(':worldedit-core')
    }
}